<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hide Organisation Menu Items_multisel_a39ec4</name>
   <tag></tag>
   <elementGuidId>d4df0e2f-8bb1-4073-b504-5671e109a409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9109e665-f141-4806-b3e9-733d47160685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-dropdownbase e-control e-multiselect e-lib</value>
      <webElementGuid>2034e79a-281d-4cab-a713-520fddbb179c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1</value>
      <webElementGuid>1fc12987-e6c3-4fd6-ba86-865a5bedee47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select items to hide from menu...</value>
      <webElementGuid>6c0d4232-d503-4252-9934-045ed8fda018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>975d10d2-bd1b-4f6d-a4c5-a3f809ba6adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72364363-a67b-4993-b5d1-14514c306ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2b04af7f-3492-46e8-9b2f-2cc6879b6553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54a5f3c5-9881-4366-9a93-a8668372d936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00f33b7b-3b7c-4ae0-9296-2d782e0e987b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d62d551e-905d-4b55-88f0-b3948aef6ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59d92ce5-3555-40e4-8cc4-41af0ff25554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>default_val</value>
      <webElementGuid>053c3d3e-43c0-4530-8a49-cab525f25d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b26b307-8045-498e-bbb2-cd6c4f0c86eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1</value>
      <webElementGuid>c94f0f05-9cea-4ca0-ab7e-5dbb675b5825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>2dd2fe8a-0bed-467c-9537-ff6745e5ad4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_0</value>
      <webElementGuid>7b78ed96-44f5-47db-8efc-03307509932b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_popup</value>
      <webElementGuid>610abb1f-998d-4513-a304-cfe976b85c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_options</value>
      <webElementGuid>da601871-92f5-42bc-a5e6-daeb475e2d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1&quot;)</value>
      <webElementGuid>8d0aaa6f-496a-44a5-a822-795f3c066144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1']</value>
      <webElementGuid>9756b9f3-6e9e-4cb0-a37c-a41b8449ff52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='matBlazor_id_4b014758-5f19-4ccb-be78-9e1494f53b0e']/form/div/div/span[3]/input</value>
      <webElementGuid>bc696fa4-134f-497b-a139-50127b554c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cc88da6d-a9e2-4001-ac8d-b004ed099cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1' and @placeholder = 'Select items to hide from menu...' and @type = 'text' and @id = 'multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1']</value>
      <webElementGuid>2978c19b-376c-474d-b0d1-50c17d66c209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
