<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Connect</name>
   <tag></tag>
   <elementGuidId>fc7eae38-f7ff-48c1-b767-43f3757f00cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>82387a6e-3117-4043-813c-62e8169a763c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-list-item   e-hide-listitem e-item-focus</value>
      <webElementGuid>2a28da1c-d279-4358-b42f-85f6388b9d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d88d1991-b414-4b82-ae9e-444e85e17ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>reports</value>
      <webElementGuid>6dc80662-a1c2-4c31-a6ac-5344c87bed6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_1</value>
      <webElementGuid>e005ef50-a57b-4366-9865-1f9f9b67ba08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connect</value>
      <webElementGuid>4004177d-3205-4eb7-8627-05c6549d1853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_1&quot;)</value>
      <webElementGuid>735bfa58-b16c-4227-a7db-cdb1e9703769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_1']</value>
      <webElementGuid>76c896d7-4c49-4503-a22d-69c060c2e9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_options']/li[2]</value>
      <webElementGuid>2639f7e0-d038-4312-af08-9fd1cceefa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[2]/following::li[1]</value>
      <webElementGuid>f7af1471-2af2-4f5d-a19a-72fa2b86c07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::li[2]</value>
      <webElementGuid>16f15790-fa34-4296-a403-7b1f4e6580d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[1]/preceding::li[1]</value>
      <webElementGuid>2e575cde-f36e-4c60-b555-8ef555ef965f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/ul/li[2]</value>
      <webElementGuid>6139a60a-0a9e-4b91-837d-d65e774d0df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_1' and (text() = 'Connect' or . = 'Connect')]</value>
      <webElementGuid>1359c909-0d14-4605-934b-2830bb42b1a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
