<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Notices</name>
   <tag></tag>
   <elementGuidId>3a553e03-5415-4ea6-ae98-db0035b91605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c62092ff-470e-443f-a00a-47d0008ef634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-list-item   e-hide-listitem e-item-focus</value>
      <webElementGuid>0d14877b-db98-454d-bd97-0b6dda1a66ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>21046be2-cb27-4837-881f-e2f230f03c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>notifications</value>
      <webElementGuid>9fea9204-2d3f-4bd9-8910-5917d8c28a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_2</value>
      <webElementGuid>4c167f11-f983-4a9e-99ae-8bf89f43269c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notices</value>
      <webElementGuid>b1d42c1a-f14f-46cf-9a6b-d50e144258de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_2&quot;)</value>
      <webElementGuid>2e497af2-a563-4981-90ed-4103881e59a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_2']</value>
      <webElementGuid>c9127634-8833-4121-8a31-4cacc0c58c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_options']/li[3]</value>
      <webElementGuid>9f11659d-3401-482b-a555-5206baa2ef37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect'])[2]/following::li[1]</value>
      <webElementGuid>befd1c14-17c8-4429-a7b9-48e07ef992e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[2]/following::li[2]</value>
      <webElementGuid>4c2e89f2-37e7-41f9-badc-db5ec68be064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/ul/li[3]</value>
      <webElementGuid>45090c89-601e-4136-bff6-b72f9ce68b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_2' and (text() = 'Notices' or . = 'Notices')]</value>
      <webElementGuid>24f6d140-e27c-419a-8ae8-cafa0a9d9c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
