<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_News</name>
   <tag></tag>
   <elementGuidId>8af724df-d947-49b4-bcaf-fef4bf78289e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>66ab84c4-f522-46c8-bbd7-31473d002524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-list-item   e-hide-listitem e-item-focus</value>
      <webElementGuid>fd2a0e04-57a2-4509-9d2a-3c87c9735fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fd843257-6469-4167-99a1-1682759bb70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>news</value>
      <webElementGuid>a305ecc6-ce6b-4968-a3b4-1ab598066c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_0</value>
      <webElementGuid>60fe5c66-6e43-460d-9431-2528d9c20acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News</value>
      <webElementGuid>b72c8fda-9328-4d0b-b4cf-8a8d25d740af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_0&quot;)</value>
      <webElementGuid>3b1e3ccf-4d58-4235-bcc1-1b4221731724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_0']</value>
      <webElementGuid>eb716fb8-8807-4a55-a9d2-3342106acc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_options']/li</value>
      <webElementGuid>45cf12f3-ce20-49e4-b89f-4a26639e18a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::li[1]</value>
      <webElementGuid>e2f7c30a-cbdc-4a19-af50-cb3e46dd8143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='help_outline'])[1]/following::li[7]</value>
      <webElementGuid>e39ad470-1628-4efb-83e7-a36ca4df0ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect'])[1]/preceding::li[1]</value>
      <webElementGuid>83b53efe-f373-44cb-9e75-b342aaea811d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notices'])[1]/preceding::li[2]</value>
      <webElementGuid>4a856cbf-8094-4105-8288-3b2730e0531c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/ul/li</value>
      <webElementGuid>975819be-c85d-44b0-8ffb-5f843d9c512a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'multiselect-6249cf39-7542-4cf9-91e1-ee0a0c0017b1_0' and (text() = 'News' or . = 'News')]</value>
      <webElementGuid>e4f9ae84-7e1a-4d98-a13e-8bac5647e23c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
